language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: K2r2W2qC+r22S73ZcgLzDOTiBiirgjfKWoR01tXTxMHO40GhBcKTDZcTOAu5tqaqUuKYkXT+ZHHG3nxHPfpJQS4Q52XMBR9cuqpnABh5ShTSmqM/0oe7W25QgtlPHSAWilosBaGpqpkATyEx2l8LX5ZuxTP1M7EScm3V95zBlcMja1Juqzu+Q4QeJLoxXp333dTZQjK+e8du6PXxS4/u6ukgcvuNu7C3SoHA4eN1+M7zsFdpkbi8jMNNYCLryV523dEcHja+QSpblWMp1+wvmF9ICcx1Qnm3awuDpv+K8FxX0kUQFugnQH0jxU9ejnGHVPiVOZrxGHe7uf4+PzYZr2L3f03pZ4zvNVgEvdOf4O0jRcuXh56Q0OC/e75kHKVjF5VbkhzO2F99OFPk78ZvM6qawLSpGE4YMMnUyjbRoDl1Pt7Q657JlEbiMHini+qsHu+YiF0atUR7XWjl17BHe3ujmp4kXRqc7uAlKugcwzCZx1FaWUrkdSoNtS5yKQLQzItzPd4V/eHH4aJT6GY/NtdzmEQ8Wko/oXrUYQJvS/fuYR70Cd0mFSZ6ooI/1Xy2cGvQK2LFOUX3p8NgeU9GBQTIQmDvlWUPRle4KHdxEcJLtcbPMe3Dyfc2MjXs+ZePJ1QFMW+LRnu1/LcVeIZegzBhmrek+m4K54AdgvlIXic=
  app: desolate-ocean-38188
  on:
    repo: cdwlighting/peepchat_api
